### ISSUE TITLE
Isuue on Windows 10 run RunCukesByCompositionGrp1_Test1.java

### ISSUE THREAD

**Issue by Jun-Yang** [bigtester/automation-test-engine#193]
-13:06:26.822 [main] WARN  o.s.c.s.FileSystemXmlApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
 -org.springframework.beans.FatalBeanException: Case database creation error!; nested exception is org.dbunit.DatabaseUnitException: Exception processing table name='STEPERELEMENTEXISTENCE'
	at org.bigtester.ate.model.data.CaseDataProcessor.postProcessBeanFactory(CaseDataProcessor.java:111)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:181)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:674)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:519)
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:140)
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:106)
	at org.bigtester.ate.model.caserunner.easyApply.CaseRunner4466021912038284171.runTest(CaseRunner4466021912038284171.java:227)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.bigtester.ate.model.project.TestProject.runSuites(TestProject.java:257)
	at org.bigtester.ate.model.project.TestProject.runSuites(TestProject.java:152)
	at org.bigtester.ate.model.project.TestProject$$FastClassBySpringCGLIB$$3ab73f18.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:58)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:58)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at org.bigtester.ate.model.project.TestProject$$EnhancerBySpringCGLIB$$a262dba5.runSuites(<generated>)
	at org.bigtester.ate.AbstractCucumberTestStepDefs.runStep(AbstractCucumberTestStepDefs.java:166)
	at org.bigtester.ate.AbstractCucumberTestStepDefs.runStep(AbstractCucumberTestStepDefs.java:299)
	at org.bigtester.ate.AbstractCucumberTestStepDefs.runCucumberStep(AbstractCucumberTestStepDefs.java:264)
	at com.cucumber.testng.examples.SearchHomePageStepdefs.homepage(SearchHomePageStepdefs.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
	at cucumber.runtime.Runtime.runStep(Runtime.java:300)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.api.testng.TestNGCucumberRunner.runCukes(TestNGCucumberRunner.java:50)
	at com.cucumber.testng.examples.RunCukesByCompositionGrp1_Test1.runCukes(RunCukesByCompositionGrp1_Test1.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: org.dbunit.DatabaseUnitException: Exception processing table name='STEPERELEMENTEXISTENCE'
	at org.dbunit.operation.AbstractBatchOperation.execute(AbstractBatchOperation.java:232)
	at org.dbunit.operation.CompositeOperation.execute(CompositeOperation.java:79)
	at org.bigtester.ate.model.data.TestDatabaseInitializer.initialize(TestDatabaseInitializer.java:275)
	at org.bigtester.ate.model.data.CaseDataProcessor.postProcessBeanFactory(CaseDataProcessor.java:105)
	... 90 common frames omitted
Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10098 table: STEPERELEMENTEXISTENCE column: IDCOLUMN
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source)
	at org.dbunit.database.statement.SimplePreparedStatement.addBatch(SimplePreparedStatement.java:80)
	at org.dbunit.database.statement.AutomaticPreparedBatchStatement.addBatch(AutomaticPreparedBatchStatement.java:70)
	at org.dbunit.operation.AbstractBatchOperation.execute(AbstractBatchOperation.java:214)
	... 93 common frames omitted
Caused by: org.hsqldb.HsqlException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10098 table: STEPERELEMENTEXISTENCE column: IDCOLUMN
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Table.enforceRowConstraints(Unknown Source)
	at org.hsqldb.Table.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementDML.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementInsert.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 98 common frames omitted
13:06:26.823 [main] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@3412a3fd: defining beans [org.springframework.aop.config.internalAutoProxyCreator,systemlogger,TestCaseLogger,TestStepResult,org.springframework.transaction.config.internalTransactionalEventListenerFactory,org.springframework.transaction.annotation.AnnotationTransactionAttributeSource#0,org.springframework.transaction.interceptor.TransactionInterceptor#0,org.springframework.transaction.config.internalTransactionAdvisor,org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.annotation.internalPersistenceAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,_DaoParent,elementInputDataDao,StepERDao,dataSource,entityManagerFactory,transactionManager,org.bigtester.ate.model.data.CaseDataProcessor#0,org.bigtester.ate.model.casestep.JavaCodedStepBeanPostProcessor#0,org.bigtester.ate.model.page.elementaction.SendKeysActionPostBeanProcessor#0,org.bigtester.ate.model.page.elementfind.ElementFinderIndexOfSameProcessor#0,StepDataLogger,repeatStepExecutionLogger,globalUtilsForTestCase,multiWindowsHandler,dbInitializer,baseERValue,myBasePageModel,myBasePageObject,baseElementAction,baseInputDataValue,indeedCaHomepage,eadTypeInSearchKeyWordQA,efSearchKeyWordInput,eaTypeKeyWordQA,dvkeyWordQA,eadClearTextInWhere,efWhere,eaClearWhereText,eadTypeLocationInWhere,eaTypeInLocation,eadTypeWindsorInWhere,eaTypeWindsor,eadClickFindJobsButton,efFindJobsButton,eaFindJobsButtonClick,eadImportCookies,efFindAllCookies,eaImportFromFile,eadExportCookies,eaExportToFile,jobSearchResult,eadClickSortByDate,efDateSortingLink,eaDateClick,eadClickNonAdsJobLink,efNonAdsJobLink,eaNonAdsJobLinkClick,aidhNonAdsJobLinkIndex,eadSwitchToApplyWindow,efApplyJobWindow,eaSwitchToWindow2,eadCloseApplyWindow,eaCloseWindow2,eadClickPagingNumber,efPageNumber,aidhPageNumber,eaPageNumberClick,applyNowPage,eadClickApplyNow,efApplyNowButton,eaApplyNowClick,eadFilloutApplicantName,efApplicantName,eaFilloutApplicantName,eadFilloutApplicantFirstName,efApplicantFirstName,eaFilloutApplicantFirstName,eadFilloutApplicantLastName,efApplicantLastName,eaFilloutApplicantLastName,eadFilloutApplicantEmail,efApplicantEmail,eaFilloutApplicantEmail,eadFilloutApplicantPhoneNumber,efApplicantPhoneNumber,eaFilloutApplicantPhoneNumber,eadApplyChooseFile,efApplyNowChooseFile,eaApplyChooseFile,eadFilloutMessage,efMessage,eaMessageSent,eadSubmitResume,efResumeSubmitButton,eaClickSubmitButton,eadContinueApplication,efContinueAppButton,eaClickContinueButton,eadAnswerYesForQ0,efQ0,eaSelectYes,eadAnswerYesForQ1,efQ1,eadAnswerYesForQ2,efQ2,eadAcceptAlertInFocus,efAlertInFocus,eaAcceptAlert,myLastPage,MyWebDriver2,stepOpenHomePage,stepTypeInSearchKeyWordQA,stepClearWhereText,stepTypeInWindsorOn,stepRepeatApplyOtherKeywordsJobs,mylaststep,testcase,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor,org.springframework.context.annotation.ConfigurationClassPostProcessor.enhancedConfigurationProcessor,eaTypeInLocation_SendKeysDataValueBean_ID,eaTypeWindsor_SendKeysDataValueBean_ID,eaFilloutApplicantName_SendKeysDataValueBean_ID,eaFilloutApplicantFirstName_SendKeysDataValueBean_ID,eaFilloutApplicantLastName_SendKeysDataValueBean_ID,eaFilloutApplicantEmail_SendKeysDataValueBean_ID,eaFilloutApplicantPhoneNumber_SendKeysDataValueBean_ID,eaApplyChooseFile_SendKeysDataValueBean_ID,eaMessageSent_SendKeysDataValueBean_ID,efApplyNowButton_elementfinderIndexOfSameElements_ID]; parent: org.springframework.beans.factory.support.DefaultListableBeanFactory@2dbd803f
 -13:06:26.936 [main] INFO  o.b.ate.model.project.TestProject - APP_LOG: Test-Info:   *****===TestProject execution ends.===*****
 -13:06:26.946 [main] INFO  o.s.c.s.FileSystemXmlApplicationContext - Closing org.springframework.context.support.FileSystemXmlApplicationContext@50d68830: startup date [Sat Jun 24 13:06:22 EDT 2017]; root of context hierarchy
 -13:06:26.946 [main] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'lifecycleProcessor'
 -13:06:26.946 [main] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@2dbd803f: defining beans [org.springframework.aop.config.internalAutoProxyCreator,org.springframework.transaction.config.internalTransactionalEventListenerFactory,org.springframework.transaction.annotation.AnnotationTransactionAttributeSource#0,org.springframework.transaction.interceptor.TransactionInterceptor#0,org.springframework.transaction.config.internalTransactionAdvisor,org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.annotation.internalPersistenceAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,_DaoParent,elementInputDataDao,StepERDao,dataSource,entityManagerFactory,transactionManager,systemlogger,TestCaseLogger,TestStepResult,beanConfig,dbInitializer,globalUtilsForTestProject,org.bigtester.ate.model.project.XmlTestCase#0,org.bigtester.ate.model.project.XmlTestCase#1,easyApply,testproject,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor,org.springframework.context.annotation.ConfigurationClassPostProcessor.enhancedConfigurationProcessor,cucumberFeatureDataInjector,cucumberDataInjector]; root of factory hierarchy
 -13:06:26.949 [main] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean '(inner bean)#76a1146d': [testproject]
 -13:06:26.949 [main] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean '(inner bean)#20b829d5#1': [(inner bean)#76a1146d]
 -13:06:26.949 [main] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean '(inner bean)#20b829d5': [easyApply]
 -13:06:26.949 [main] DEBUG o.s.b.f.s.DisposableBeanAdapter - Invoking destroy() on bean with name 'entityManagerFactory'
 -13:06:26.949 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'jpaData'
 -13:06:26.949 [main] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean 'org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter#30404dba': [entityManagerFactory]
 -

**Comment by bigtester-prot** [comment]
Try delete the db data file under data folder in the cucumber project
folder.

**Comment by Jun-Yang** [comment]
After delete the db data file, it works

**Comment by Jun-Yang** [comment]
Solved
