### ISSUE TITLE
run test case error (indeedJobApplication)

### ISSUE THREAD

**Issue by happygirlcici** [bigtester/automation-test-engine#200]
[INFO] HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
Tests run: 20, Failures: 7, Errors: 0, Skipped: 13, Time elapsed: 14.347 sec <<< FAILURE! - in TestSuite
javaCodedStepTest(org.bigtester.ate.test.model.casestep.JavaCodedStepTest)  Time elapsed: 0.031 sec  <<< FAILURE!
java.lang.NoClassDefFoundError: org/openqa/selenium/remote/SessionNotFoundException
	at org.bigtester.ate.test.model.casestep.JavaCodedStepTest.javaCodedStepTest(JavaCodedStepTest.java:54)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.SessionNotFoundException
	at org.bigtester.ate.test.model.casestep.JavaCodedStepTest.javaCodedStepTest(JavaCodedStepTest.java:54)

stepException(org.bigtester.ate.test.model.casestep.StepExecExpectionTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.NoClassDefFoundError: org/openqa/selenium/remote/SessionNotFoundException
	at org.bigtester.ate.test.model.casestep.StepExecExpectionTest.stepException(StepExecExpectionTest.java:67)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.SessionNotFoundException
	at org.bigtester.ate.test.model.casestep.StepExecExpectionTest.stepException(StepExecExpectionTest.java:67)

assignValueEADTest(org.bigtester.ate.test.model.page.elementaction.AssignValueActionTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.NoClassDefFoundError: org/openqa/selenium/remote/SessionNotFoundException
	at org.bigtester.ate.test.model.page.elementaction.AssignValueActionTest.assignValueEADTest(AssignValueActionTest.java:65)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.SessionNotFoundException
	at org.bigtester.ate.test.model.page.elementaction.AssignValueActionTest.assignValueEADTest(AssignValueActionTest.java:65)

mainTest(org.bigtester.ate.test.model.page.elementaction.DropdownSelectActionTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.NoClassDefFoundError: org/openqa/selenium/remote/SessionNotFoundException
	at org.bigtester.ate.test.model.page.elementaction.DropdownSelectActionTest.mainTest(DropdownSelectActionTest.java:58)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.SessionNotFoundException
	at org.bigtester.ate.test.model.page.elementaction.DropdownSelectActionTest.mainTest(DropdownSelectActionTest.java:58)

springTestContextPrepareTestInstance(org.bigtester.ate.test.model.page.elementaction.ExportAsFileActionTest)  Time elapsed: 0.584 sec  <<< FAILURE!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.FatalBeanException: Case database creation error!; nested exception is org.dbunit.DatabaseUnitException: Exception processing table name='STEPERELEMENTEXISTENCE'
Caused by: org.dbunit.DatabaseUnitException: Exception processing table name='STEPERELEMENTEXISTENCE'
Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10098 table: STEPERELEMENTEXISTENCE column: IDCOLUMN
Caused by: org.hsqldb.HsqlException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10098 table: STEPERELEMENTEXISTENCE column: IDCOLUMN

springTestContextPrepareTestInstance(org.bigtester.ate.test.model.page.elementfind.CookiesFindAllTest)  Time elapsed: 0.494 sec  <<< FAILURE!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.FatalBeanException: Case database creation error!; nested exception is org.dbunit.DatabaseUnitException: Exception processing table name='STEPERELEMENTEXISTENCE'
Caused by: org.dbunit.DatabaseUnitException: Exception processing table name='STEPERELEMENTEXISTENCE'
Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10098 table: STEPERELEMENTEXISTENCE column: IDCOLUMN
Caused by: org.hsqldb.HsqlException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10098 table: STEPERELEMENTEXISTENCE column: IDCOLUMN

springTestContextPrepareTestInstance(org.bigtester.ate.test.model.page.page.CookiesManagerTest)  Time elapsed: 0.514 sec  <<< FAILURE!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.FatalBeanException: Case database creation error!; nested exception is org.dbunit.DatabaseUnitException: Exception processing table name='STEPERELEMENTEXISTENCE'
Caused by: org.dbunit.DatabaseUnitException: Exception processing table name='STEPERELEMENTEXISTENCE'
Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10098 table: STEPERELEMENTEXISTENCE column: IDCOLUMN
Caused by: org.hsqldb.HsqlException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10098 table: STEPERELEMENTEXISTENCE column: IDCOLUMN

Results :

Failed tests: 
  JavaCodedStepTest>AbstractTestNGSpringContextTests.run:175->javaCodedStepTest:54->BigtesterProjectTest.getTestPage:111 » NoClassDefFound
  StepExecExpectionTest>AbstractTestNGSpringContextTests.run:175->stepException:67->BigtesterProjectTest.getTestPage:111 » NoClassDefFound
  AssignValueActionTest>AbstractTestNGSpringContextTests.run:175->assignValueEADTest:65->BigtesterProjectTest.getTestPage:111 » NoClassDefFound
  DropdownSelectActionTest>AbstractTestNGSpringContextTests.run:175->mainTest:58->BigtesterProjectTest.getTestPage:111 » NoClassDefFound
  ExportAsFileActionTest>AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance:149 » IllegalState
  CookiesFindAllTest>AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance:149 » IllegalState
  CookiesManagerTest>AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance:149 » IllegalState

Tests run: 20, Failures: 7, Errors: 0, Skipped: 13

[ERROR] There are test failures.

Please refer to C:\Users\Chen Chen\Documents\01Internship\ATE\automation-test-engine-cucumber\org.bigtester.ate.core\target\surefire-reports for the individual test results.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ org.bigtester.ate.core ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ org.bigtester.ate.core ---
[INFO] Installing C:\Users\Chen Chen\Documents\01Internship\ATE\automation-test-engine-cucumber\org.bigtester.ate.core\target\org.bigtester.ate.core-0.2.0-SNAPSHOT.jar to C:\Users\Chen Chen\.m2\repository\org\bigtester\org.bigtester.ate.core\0.2.0-SNAPSHOT\org.bigtester.ate.core-0.2.0-SNAPSHOT.jar
[INFO] Installing C:\Users\Chen Chen\Documents\01Internship\ATE\automation-test-engine-cucumber\org.bigtester.ate.core\pom.xml to C:\Users\Chen Chen\.m2\repository\org\bigtester\org.bigtester.ate.core\0.2.0-SNAPSHOT\org.bigtester.ate.core-0.2.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.642 s
[INFO] Finished at: 2017-08-16T22:38:19-04:00
[INFO] Final Memory: 28M/305M
[INFO] ------------------------------------------------------------------------

@peidong-hu run test case error (indeedJobApplication)
**javaCodedStepTest(org.bigtester.ate.test.model.casestep.JavaCodedStepTest)  Time elapsed: 0.031 sec  <<< FAILURE!
java.lang.NoClassDefFoundError: org/openqa/selenium/remote/SessionNotFoundException
	at**

**Comment by bigtester-prot** [comment]
I think this is an error related to the browser. Is the browser started?

**Comment by happygirlcici** [comment]
Yes, my browser is chrome,it is open

**Comment by bigtester-prot** [comment]
what is the version of the browser?

**Comment by peidong-hu** [comment]
Try delete the data folder in your project.

**Comment by happygirlcici** [comment]
fixed it by rerun in new version on master_jun
