### ISSUE TITLE
Session Not Found Exception 

### ISSUE THREAD

**Issue by happygirlcici** [bigtester/automation-test-engine#207]
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.SessionNotFoundException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 55 common frames omitted

**Comment by happygirlcici** [comment]
fixed by deupgrade dependency
