### ISSUE TITLE
Unit Test Failure-bad magic number

### ISSUE THREAD

**Issue by happygirlcici** [bigtester/automation-test-engine#209]
maven install and then got error message

can not run indeedJobSearch test

11:44:34.990 [main] DEBUG org.reflections.Reflections - could not scan file org/bigtester/ate/xmlschema/ate.xsd in url file:/C:/Users/Chen%20Chen/git/automation-test-engine/org.bigtester.ate.core/target/classes/ with scanner SubTypesScanner
org.reflections.ReflectionsException: could not create class object from file org/bigtester/ate/xmlschema/ate.xsd
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:32)
	at org.reflections.Reflections.scan(Reflections.java:253)
	at org.reflections.Reflections.scan(Reflections.java:202)
	at org.reflections.Reflections.<init>(Reflections.java:123)
	at org.reflections.Reflections.<init>(Reflections.java:168)
	at org.reflections.Reflections.<init>(Reflections.java:141)
	at org.bigtester.ate.TestProjectRunner.registerXsdNameSpaceParsers(TestProjectRunner.java:314)
	at org.bigtester.ate.test.BaseATETest.<init>(BaseATETest.java:124)
	at org.bigtester.ate.test.BigtesterProjectTest.<init>(BigtesterProjectTest.java:41)
	at org.bigtester.ate.test.AbstractBigtesterStepTest.<init>(AbstractBigtesterStepTest.java:41)
	at org.bigtester.ate.test.model.page.elementaction.AssignValueActionTest.<init>(AssignValueActionTest.java:48)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:382)
	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:295)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:118)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:183)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:128)
	at org.testng.TestRunner.initMethods(TestRunner.java:416)
	at org.testng.TestRunner.init(TestRunner.java:242)
	at org.testng.TestRunner.init(TestRunner.java:212)
	at org.testng.TestRunner.<init>(TestRunner.java:166)
	at org.testng.remote.support.RemoteTestNG6_9_7$1.newTestRunner(RemoteTestNG6_9_7.java:27)
	at org.testng.remote.support.RemoteTestNG6_9_7$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_9_7.java:63)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:587)
	at org.testng.SuiteRunner.init(SuiteRunner.java:161)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:114)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1266)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1253)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1107)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: org.reflections.ReflectionsException: could not create class file from ate.xsd
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:102)
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:24)
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30)
	... 36 common frames omitted
Caused by: java.io.IOException: bad magic number: 3c3f786d
	at javassist.bytecode.ClassFile.read(ClassFile.java:803)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:148)
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:100)
	... 38 common frames omitted
11:44:34.991 [main] DEBUG org.reflections.Reflections - could not scan file org/bigtester/ate/xmlschema/ate.xsd in url file:/C:/Users/Chen%20Chen/git/automation-test-engine/org.bigtester.ate.core/target/classes/ with scanner TypeAnnotationsScanner
org.reflections.ReflectionsException: could not create class object from file org/bigtester/ate/xmlschema/ate.xsd
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:32)
	at org.reflections.Reflections.scan(Reflections.java:253)
	at org.reflections.Reflections.scan(Reflections.java:202)
	at org.reflections.Reflections.<init>(Reflections.java:123)
	at org.reflections.Reflections.<init>(Reflections.java:168)
	at org.reflections.Reflections.<init>(Reflections.java:141)
	at org.bigtester.ate.TestProjectRunner.registerXsdNameSpaceParsers(TestProjectRunner.java:314)
	at org.bigtester.ate.test.BaseATETest.<init>(BaseATETest.java:124)
	at org.bigtester.ate.test.BigtesterProjectTest.<init>(BigtesterProjectTest.java:41)
	at org.bigtester.ate.test.AbstractBigtesterStepTest.<init>(AbstractBigtesterStepTest.java:41)
	at org.bigtester.ate.test.model.page.elementaction.AssignValueActionTest.<init>(AssignValueActionTest.java:48)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:382)
	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:295)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:118)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:183)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:128)
	at org.testng.TestRunner.initMethods(TestRunner.java:416)
	at org.testng.TestRunner.init(TestRunner.java:242)
	at org.testng.TestRunner.init(TestRunner.java:212)
	at org.testng.TestRunner.<init>(TestRunner.java:166)
	at org.testng.remote.support.RemoteTestNG6_9_7$1.newTestRunner(RemoteTestNG6_9_7.java:27)
	at org.testng.remote.support.RemoteTestNG6_9_7$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_9_7.java:63)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:587)
	at org.testng.SuiteRunner.init(SuiteRunner.java:161)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:114)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1266)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1253)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1107)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: org.reflections.ReflectionsException: could not create class file from ate.xsd
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:102)
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:24)
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30)
	... 36 common frames omitted
Caused by: java.io.IOException: bad magic number: 3c3f786d
	at javassist.bytecode.ClassFile.read(ClassFile.java:803)

**Comment by Jun-Yang** [comment]
Change the dependency version: hibernate-entitymanager -> 4.3.8.final
reflections -> 0.9.10
Fix the problem
